add_rules("mode.debug")
set_warnings("all")
set_languages("c++17")
add_requires("abseil",{system = false})
add_requires("fmt",{system = false})
add_requires("gtest",{system = false})
add_requires("folly",{system = false})

-- Ensure proper SDK sysroot for C++ standard headers on macOS
if is_plat("macosx") then
    add_cxxflags("-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk", {force = true})
    add_cxxflags("-g", {force = true})
    add_ldflags("-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk", {force = true})
end

target("bbolt_pp")
    set_kind("static")
    set_languages("c++17")
    add_packages("abseil","folly")
    add_files("bucket.cpp","compact.cpp","cursor.cpp","db.cpp","file.cpp","freelist.cpp","freelist_hmap.cpp","node.cpp","page.cpp","tx.cpp","logger.cpp","mlock.cpp","utils.cpp","verify.cpp")

target("test_basic")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/test_basic.cpp")

target("test_simple")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/test_simple.cpp")

target("test_db")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/test_db.cpp")

target("test_bucket")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/test_bucket.cpp")

target("bbolt")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt")
    add_files("cmd/bbolt/main.cpp")

target("test_db_simple")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/db_test_simple.cpp")

target("test_bucket_simple")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/bucket_test_simple.cpp")

-- New test targets
target("test_node")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/node_test.cpp")

target("test_tx_check")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/tx_check_test.cpp")

target("test_utils")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/utils_test.cpp")

target("test_concurrent")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/concurrent_test.cpp")

target("test_db_whitebox")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/db_whitebox_test.cpp")

target("test_manydbs")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/manydbs_test.cpp")

target("test_unix")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/unix_test.cpp")

target("test_simulation")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/simulation_test.cpp")

target("test_movebucket")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/movebucket_test.cpp")

target("test_allocate")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/allocate_test.cpp")

target("test_quick")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/quick_test.cpp")

target("test_tx_stats")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/tx_stats_test.cpp")

target("test_simulation_no_freelist_sync")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/simulation_no_freelist_sync_test.cpp")

-- Internal test targets
target("test_internal_freelist_array")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/internal_freelist_array_test.cpp")

target("test_internal_freelist")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/internal_freelist_test.cpp")

target("test_internal_freelist_hashmap")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/internal_freelist_hashmap_test.cpp")

target("test_internal_common_page")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/internal_common_page_test.cpp")

target("test_internal_surgeon")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/internal_surgeon_test.cpp")

target("test_internal_tests_tx_check")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/internal_tests_tx_check_test.cpp")

-- Command tool test targets
target("test_cmd_bbolt_command")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/cmd_bbolt_command_test.cpp")

-- Special test targets
target("test_special_dmflakey")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/special_dmflakey_test.cpp")

target("test_special_failpoint")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/special_failpoint_test.cpp")

target("test_special_robustness")
    set_kind("binary")
    set_languages("c++17")
    add_deps("bbolt_pp")
    add_packages("abseil", "fmt", "gtest")
    add_files("tests/special_robustness_test.cpp")
